### PR TITLE
changes to work with no-std

### PR DESCRIPTION
**Pull request by carl-wallace**
With these changes in place I can build a no-std project that uses this crate against the wasm32-unknown-unknown target.

### CODE REVIEW

**Comment by carl-wallace** [comment]
Will reopen after feature gating no-std.

**Comment by carl-wallace** [comment]
Did not need a feature gate, just needed to address doctests and remove an explicit std::string reference. All tests now work for workspace with cargo hack test --feature-powerset and works from my project with a no-std target.

**Comment by vkill** [comment]
Thank you @carl-wallace

**Comment by vkill** [comment]
[0.3.0](https://github.com/bk-rs/serde-ext/commit/fa6200e3d393e9b1f7988a4688b552564f79e3df)

**Comment by vkill** [comment]
Release 0.3.2

**Pull request merged**
